/* empty css                      */import{a as u,N as L}from"./assets/vendor-77e6b4aa.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))s(n);new MutationObserver(n=>{for(const i of n)if(i.type==="childList")for(const r of i.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&s(r)}).observe(document,{childList:!0,subtree:!0});function o(n){const i={};return n.integrity&&(i.integrity=n.integrity),n.referrerpolicy&&(i.referrerPolicy=n.referrerpolicy),n.crossorigin==="use-credentials"?i.credentials="include":n.crossorigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(n){if(n.ep)return;n.ep=!0;const i=o(n);fetch(n.href,i)}})();u.defaults.baseURL="https://books-backend.p.goit.global/";async function y(){return(await u.get("/books/category-list")).data}async function b(){return(await u.get("/books/top-books")).data}async function v(e){return(await u.get(`/books/${e}`)).data}b();function w(e,t){const o=t===0?"mobile-visible":"",s=t<3?"tablet-visible":"",n=t<5?"desktop-visible":"";return`

  <li id="${e._id}" class="listener" onclick="openModal('${e._id}')">
        <div class="book-category-card ${o} ${s} ${n}">

        <img class="bookByCategory-img" src="${e.book_image}" alt="${e.title}">
        <div class="book-category-details">
          <h3 class="book-category-title">${e.title}</h3>
          <p class="book-category-author">${e.author}</p>
        </div>
      </div>
    </li>
  `}function S(e,t){const o=document.querySelector(`.book-category[data-category="${e}"] .books-category-list`);if(o){const s=t.map((n,i)=>w(n,i)).join("");o.innerHTML=s}}function C(){b().then(e=>{e.forEach(t=>{S(t.list_name,t.books)})}).catch(e=>console.error("Помилка при завантаженні категорій книг:",e))}function E(e){const t=document.createElement("div");t.className="book-category",t.setAttribute("data-category",e);const o=document.createElement("div");o.className="category-title";const s=document.createElement("span");s.textContent=e.toUpperCase(),o.appendChild(s);const n=document.createElement("div");n.className="books";const i=document.createElement("ul");i.className="books-category-list",n.appendChild(i);const r=document.createElement("button");return r.className="see-more",r.textContent="SEE MORE",t.appendChild(o),t.appendChild(n),t.appendChild(r),t}function B(){const e=document.querySelector(".best-sellers-list");y().then(t=>{t.forEach(o=>{const s=E(o.list_name);e.appendChild(s)})}).catch(t=>console.error("Помилка при завантаженні категорій книг:",t))}document.addEventListener("DOMContentLoaded",B);document.addEventListener("DOMContentLoaded",C);const A=document.querySelector(".category-list-container");y().then(e=>e.map(t=>`<li class="category-list-item">
    <button class="category-btn" type="button">
      ${t.list_name}
    </button>
  </li>`).join("")).then(e=>A.insertAdjacentHTML("afterbegin",e));const M=document.querySelector(".category-btn");M.addEventListener("click",_);function _(e){console.log(e)}document.addEventListener("DOMContentLoaded",e=>{const t=document.getElementById("theme-toggle");t.addEventListener("change",()=>{t.checked?document.body.classList.add("dark-theme"):document.body.classList.remove("dark-theme")});const o=document.getElementById("theme-toggle"),s=document.getElementById("theme-toggle-label");o.addEventListener("change",()=>{o.checked?(s.classList.remove("light-theme"),s.classList.add("dark-theme")):(s.classList.remove("dark-theme"),s.classList.add("light-theme"))})});function q(){var e=window.location.pathname,t=document.querySelectorAll(".nav-list li a");t.forEach(function(o){o.parentNode.classList.remove("nav-bar-active"),(o.getAttribute("href")===`..${e}`||o.getAttribute("href")===`.${e}`||o.getAttribute("href")===`${e}`)&&o.parentNode.classList.add("nav-bar-active")})}window.addEventListener("DOMContentLoaded",q);const c=document.querySelector(".foundations-list"),N=[{title:"Save the Children",url:"https://www.savethechildren.net/what-we-do/emergencies/ukraine-crisis",img:"./img/supportsLogo/support_9.png"},{title:"Project HOPE",url:"https://www.projecthope.org/country/ukraine/",img:"./img/supportsLogo/support_1.png"},{title:"UNITED24",url:"https://u24.gov.ua/uk",img:"./img/supportsLogo/support_2.png"},{title:"International Medical Corps",url:"https://internationalmedicalcorps.org/country/ukraine/",img:"./img/supportsLogo/support_3.png"},{title:"Medicins Sans Frontieres",url:"https://www.msf.org/ukraine",img:"./img/supportsLogo/support_4.png"},{title:"RAZOM",url:"https://www.razomforukraine.org/",img:"./img/supportsLogo/support_5.png"},{title:"Action against hunger",url:"https://www.actionagainsthunger.org/location/europe/ukraine/",img:"./img/supportsLogo/support_6.png"},{title:"World vision",url:"https://www.wvi.org/emergencies/ukraine",img:"./img/supportsLogo/support_7.png"},{title:"Serhiy Prytula Charity Foundation",url:"https://prytulafoundation.org/en",img:"./img/supportsLogo/support_8.png"}],$=N.map((e,t,o)=>` <li class="support-foundation">
      <span>0${t+1}</span>
     <a href="${e.url}" target="_blank"> <img class="foundation-logo" src="${e.img}" alt="${e.title}"></a>
    </li>`).join("");c.insertAdjacentHTML("afterbegin",$);const d=document.querySelector(".support-slider-button");d.addEventListener("click",T);let l=!1;d.innerHTML='  <svg with="20" height="20"><use href="./img/sprite.svg#icon-down-arrow"></use></svg>';function T(){if(!l&&(c.scrollBy(0,300),c.scrollTop+c.offsetHeight>=c.scrollHeight)){d.innerHTML='  <svg with="20" height="20"><use href="./img/sprite.svg#icon-up-arrow"></use></svg>',l=!0;return}if(l&&(c.scrollBy(0,-300),c.scrollTop===0)){d.innerHTML='  <svg with="20" height="20"><use href="./img/sprite.svg#icon-down-arrow"></use></svg>',l=!1;return}}window.openModal=O;const a=document.querySelector(".modal");async function O(e){v(e).then(t=>{a.setAttribute("data-book",JSON.stringify(t)),j(t)}).catch(t=>{L.Notify.failure("Помилка при отриманні даних про книгу:")}),a.classList.add("open"),document.body.style.overflow="hidden"}const I=a.querySelector(".modal-body"),D=a.querySelector(".modal-close"),m=function(){a.classList.remove("open"),document.body.style.overflow="",console.log()};D.addEventListener("click",m);I.addEventListener("click",m);document.addEventListener("keydown",function(e){e.key==="Escape"&&m()});const g=a.querySelector(".add-to-list"),x=a.querySelector(".under-btn-text");g.addEventListener("click",function(e){e.stopPropagation();const t=JSON.parse(a.getAttribute("data-book"));let o=JSON.parse(localStorage.getItem("shoppingList"))||[];o.includes(t._id)?o=o.filter(n=>n!==t._id):o.push(t),localStorage.setItem("shoppingList",JSON.stringify(o));const s=k(o);x.style.display=s?"block":"none"});function k(e){const t=a.querySelector(".book-title").textContent,o=e.includes(t);return o?g.textContent="Remove from the shopping list":g.textContent="Add to shopping list",o}const H=JSON.parse(localStorage.getItem("shoppingList"))||[];k(H);function j(e){var h,f;const t=document.querySelector(".book-cover"),o=document.querySelector(".book-title"),s=document.querySelector(".book-author"),n=document.querySelector(".book-description"),i=document.querySelector(".marketplace-logo.amazon"),r=document.querySelector(".marketplace-logo.apple-books");t.src=e.book_image,t.alt=e.title,o.textContent=e.title,s.textContent=e.author,n.textContent=e.description||"No description available",i.href=((h=e.buy_links.find(p=>p.name==="Amazon"))==null?void 0:h.url)||"",r.href=((f=e.buy_links.find(p=>p.name==="Apple Books"))==null?void 0:f.url)||""}
//# sourceMappingURL=commonHelpers.js.map
